### ISSUE TITLE
(FUNCIONALIDAD) - Campo de Status personalizado para cliente vs admin

### ISSUE THREAD

**Issue by ismgonza** [Security-Consulting-Group/scg_portal#12]
En tareas, en el campo de STATUS, para cliente que se muestre un campo texto, y para admin q sea un select 

Relacionado a #11

**Comment by Pino835** [comment]
Para el cliente, el campo de status se vuelve un campo de texto y no se editar, además el botón está deshabilitado. Para el admin, tiene el campo habilitado para cambiar el estado de la tarea.
